import React, { memo, useMemo } from 'react';
import { motion } from 'framer-motion';
import { useParams, useNavigate, Link } from 'react-router-dom';
import {
    Download, Printer, Share2, ArrowLeft, FileText, Calendar,
    User, AlertTriangle, BarChart3, CheckCircle
} from 'lucide-react';
import Card from '../components/common/Card';
import Button from '../components/common/Button';
import Badge from '../components/common/Badge';
import { useReports } from '../context/ReportContext';
import { useDefects } from '../context/DefectContext';
import { useToast } from '../components/common/Toast';
import { formatDateTime } from '../utils/formatters';
import { generatePDF } from '../utils/pdfGenerator';

const container = {
    hidden: { opacity: 0 },
    show: { opacity: 1, transition: { staggerChildren: 0.1 } },
};
const item = {
    hidden: { opacity: 0, y: 20 },
    show: { opacity: 1, y: 0 },
};

const ReportViewerPage = memo(() => {
    const { id } = useParams();
    const navigate = useNavigate();
    const { reports } = useReports();
    const { defects } = useDefects(); // Get defects to pass to PDF generator
    const toast = useToast();

    // ... (report memo logic)

    const report = useMemo(() => {
        return reports.find(r => r.id === id) || reports[0] || null;
    }, [reports, id]);

    const handleDownload = () => {
        if (report) {
            generatePDF(report, defects); // Pass defects (or fetch them if filtered by report)
            toast.success('Report downloaded');
        }
    };

    const handlePrint = () => {
        window.print();
        toast.info('Print dialog opened');
    };

    const handleShare = () => {
        const url = window.location.href;
        navigator.clipboard?.writeText(url);
        toast.success('Report link copied to clipboard');
    };

    if (!report) {
        return (
            <div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-8">
                <div className="text-center py-20">
                    <FileText className="w-16 h-16 text-gray-600 mx-auto mb-4" />
                    <h2 className="text-xl font-semibold text-white mb-2">Report Not Found</h2>
                    <p className="text-gray-400 mb-6">The report you're looking for doesn't exist.</p>
                    <Link to="/dashboard">
                        <Button icon={ArrowLeft}>Back to Dashboard</Button>
                    </Link>
                </div>
            </div>
        );
    }

    const severity = report.severityDistribution;
    const total = severity.low + severity.medium + severity.high + severity.critical;

    return (
        <div className="max-w-[1400px] mx-auto px-4 sm:px-6 py-8">
            <motion.div variants={container} initial="hidden" animate="show" className="space-y-6">
                {/* Header bar */}
                <motion.div variants={item} className="glass-panel rounded-xl p-4 sm:p-6">
                    <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                        <div className="flex items-center gap-4">
                            <div className="flex flex-col">
                                <div className="flex items-center gap-2 mb-1">
                                    <span className="text-sm text-gray-400">Critical Defects</span>
                                </div>
                                <div className="flex items-baseline gap-2">
                                    <span className="text-3xl font-bold text-white">{report.totalDefects}</span>
                                    <span className="text-sm text-gray-500">of {total}</span>
                                </div>
                                <span className="text-xs text-gray-500">{report.severityDistribution.critical} critical found</span>
                            </div>
                            <div className="hidden sm:block w-px h-12 bg-white/10 mx-2" />
                            <div className="hidden sm:block">
                                <p className="text-sm text-gray-400">{report.missionName}</p>
                                <p className="text-xs text-gray-500">Generated by {report.generatedBy} • {formatDateTime(report.generationDate)}</p>
                            </div>
                        </div>

                        <div className="flex flex-wrap items-center gap-2">
                            <Button variant="secondary" size="sm" icon={Download} onClick={handleDownload}>Download</Button>
                            <Button variant="ghost" size="sm" icon={Printer} onClick={handlePrint}>Print</Button>
                            <Button variant="ghost" size="sm" icon={Share2} onClick={handleShare}>Share</Button>
                            <Link to="/dashboard">
                                <Button variant="ghost" size="sm" icon={ArrowLeft}>Back to Dashboard</Button>
                            </Link>
                        </div>
                    </div>
                </motion.div>

                {/* Report Content */}
                <motion.div variants={item}>
                    <Card title="Defect Table" icon={AlertTriangle} animate={false}>
                        {/* Simulated PDF Report */}
                        <div className="bg-white rounded-lg p-6 sm:p-8 text-gray-900 min-h-[500px]">
                            {/* Report Header */}
                            <div className="flex items-start justify-between border-b border-gray-200 pb-4 mb-6">
                                <div className="flex items-center gap-3">
                                    <div className="w-12 h-12 bg-gray-100 rounded-lg flex items-center justify-center">
                                        <span className="text-2xl font-bold text-blue-600">PDF</span>
                                    </div>
                                    <div>
                                        <h2 className="text-xl font-bold text-gray-900">Report Structure Post</h2>
                                        <p className="text-sm text-gray-500">
                                            Infrastructure inspection report • {report.missionName}
                                        </p>
                                        <p className="text-xs text-gray-400 mt-1">
                                            Generated: {formatDateTime(report.generationDate)}
                                        </p>
                                    </div>
                                </div>
                                <Button variant="ghost" size="sm" className="text-gray-500">
                                    <CheckCircle className="w-4 h-4 mr-1" /> Certified
                                </Button>
                            </div>

                            {/* Report Body - Two columns */}
                            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                {/* Left - Report Content */}
                                <div className="space-y-4">
                                    {/* TOC */}
                                    <div className="space-y-1">
                                        {['Executive Summary', 'Findings', 'Analysis', 'Recommendations', 'Appendix'].map((section, i) => (
                                            <p key={section} className="text-sm text-blue-600 cursor-pointer hover:underline">
                                                {i + 1}. {section}
                                            </p>
                                        ))}
                                    </div>

                                    {/* Simulated images */}
                                    <div className="grid grid-cols-2 gap-3">
                                        <div className="aspect-video bg-gray-100 rounded-lg flex items-center justify-center">
                                            <span className="text-xs text-gray-400">Infrastructure View 1</span>
                                        </div>
                                        <div className="aspect-video bg-gray-100 rounded-lg flex items-center justify-center relative">
                                            <span className="text-xs text-gray-400">Infrastructure View 2</span>
                                            <div className="absolute top-2 right-2 w-8 h-8 border-2 border-red-500 opacity-60" />
                                        </div>
                                    </div>

                                    <div className="text-xs text-gray-600 leading-relaxed space-y-2">
                                        <p>This inspection report documents findings from the aerial survey conducted using drone-mounted
                                            cameras and AI-powered defect detection systems. The analysis covers structural integrity assessment
                                            including crack detection, corrosion monitoring, and deformation analysis.</p>
                                        <p><strong>Maintenance Recommendations:</strong> Based on the identified defects, immediate attention
                                            is required for {severity.critical} critical issues. Regular monitoring schedule recommended for
                                            medium and low severity findings.</p>
                                    </div>
                                </div>

                                {/* Right - Defect Details */}
                                <div className="space-y-4">
                                    <div>
                                        <h3 className="text-base font-bold text-gray-900 mb-2">Defect Distribution</h3>
                                        <p className="text-xs text-gray-500 mb-3">Findings by severity level</p>
                                    </div>

                                    {/* Simulated detection image */}
                                    <div className="aspect-video bg-gray-100 rounded-lg flex items-center justify-center relative">
                                        <span className="text-xs text-gray-400">Detection Overlay</span>
                                        <div className="absolute top-3 left-3 bg-red-500 text-white text-[10px] px-2 py-0.5 rounded">
                                            Defect Detected
                                        </div>
                                    </div>

                                    <div className="text-sm space-y-1.5">
                                        <div className="flex justify-between">
                                            <span className="text-gray-500">ID</span>
                                            <span className="font-mono text-gray-700">{report.id}</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span className="text-gray-500">Severity</span>
                                            <span className="text-gray-700">Mixed ({severity.critical} critical)</span>
                                        </div>
                                        <div className="flex justify-between">
                                            <span className="text-gray-500">Confidence</span>
                                            <span className="text-gray-700">{report.avgConfidence}%</span>
                                        </div>
                                    </div>

                                    {/* Pie Chart Placeholder */}
                                    <div className="flex justify-center">
                                        <div className="relative w-24 h-24">
                                            <svg viewBox="0 0 100 100" className="w-24 h-24 -rotate-90">
                                                <circle cx="50" cy="50" r="40" fill="none" stroke="#e5e7eb" strokeWidth="12" />
                                                <circle cx="50" cy="50" r="40" fill="none" stroke="#00ff88" strokeWidth="12"
                                                    strokeDasharray={`${(severity.low / total) * 251.3} 251.3`} strokeDashoffset="0" />
                                                <circle cx="50" cy="50" r="40" fill="none" stroke="#ffaa00" strokeWidth="12"
                                                    strokeDasharray={`${(severity.medium / total) * 251.3} 251.3`}
                                                    strokeDashoffset={`${-(severity.low / total) * 251.3}`} />
                                            </svg>
                                            <div className="absolute inset-0 flex items-center justify-center">
                                                <span className="text-sm font-bold text-gray-700">{report.avgConfidence}%</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* Player controls footer */}
                            <div className="mt-6 pt-4 border-t border-gray-200 flex items-center justify-between text-xs text-gray-400">
                                <span>Page 1 of 5</span>
                                <span>ARIADOS Infrastructure Report v2.0</span>
                            </div>
                        </div>
                    </Card>
                </motion.div>

                {/* Bottom controls */}
                <motion.div variants={item} className="flex items-center justify-center gap-3 py-4">
                    <button className="p-2 rounded-lg text-gray-400 hover:text-white hover:bg-white/5 transition-all">
                        <ArrowLeft className="w-5 h-5" />
                    </button>
                    <button className="p-2 rounded-lg text-gray-400 hover:text-white hover:bg-white/5 transition-all">
                        ▶
                    </button>
                    <button className="p-2 rounded-lg text-gray-400 hover:text-white hover:bg-white/5 transition-all">
                        ⏭
                    </button>
                    <div className="flex-1 max-w-md mx-4 h-1.5 bg-white/5 rounded-full cursor-pointer">
                        <div className="h-full w-1/3 bg-gradient-to-r from-cyan-400 to-cyan-500 rounded-full relative">
                            <div className="absolute right-0 top-1/2 -translate-y-1/2 w-3 h-3 rounded-full bg-cyan-400 shadow-glow-sm" />
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        <Monitor className="w-4 h-4 text-gray-500" />
                        <Settings className="w-4 h-4 text-gray-500" />
                    </div>
                </motion.div>
            </motion.div>
        </div>
    );
});

const Monitor = ({ className }) => (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="2" y="3" width="20" height="14" rx="2" ry="2" />
        <line x1="8" y1="21" x2="16" y2="21" />
        <line x1="12" y1="17" x2="12" y2="21" />
    </svg>
);

const Settings = ({ className }) => (
    <svg className={className} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <circle cx="12" cy="12" r="3" />
        <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06A1.65 1.65 0 0 0 19.32 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" />
    </svg>
);

ReportViewerPage.displayName = 'ReportViewerPage';
export default ReportViewerPage;
