import jsPDF from 'jspdf';
import 'jspdf-autotable';
import { formatDateTime } from './formatters';

export const generatePDF = (report, defects) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    const pageHeight = doc.internal.pageSize.height;

    // --- Header ---
    doc.setFillColor(6, 182, 212); // Cyan-500
    doc.rect(0, 0, pageWidth, 20, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('ARIADOS Infrastructure Report', 14, 13);

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    const dateStr = formatDateTime(new Date());
    doc.text(`Generated: ${dateStr}`, pageWidth - 14, 13, { align: 'right' });

    // --- Report Metadata ---
    let yPos = 35;
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Mission Summary', 14, yPos);

    yPos += 8;
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Mission Name: ${report.missionName}`, 14, yPos);
    doc.text(`Report ID: ${report.id}`, 110, yPos);
    yPos += 6;
    doc.text(`Generated By: ${report.generatedBy}`, 14, yPos);
    doc.text(`Total Defects Found: ${report.totalDefects}`, 110, yPos);

    // --- Metrics Section ---
    yPos += 15;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Severity Distribution', 14, yPos);

    // Draw little colored boxes for severity
    const drawLegend = (x, y, color, label, count) => {
        doc.setFillColor(...color);
        doc.circle(x, y - 1, 1.5, 'F');
        doc.setFontSize(9);
        doc.setTextColor(60, 60, 60);
        doc.text(`${label}: ${count}`, x + 4, y);
    };

    yPos += 8;
    drawLegend(14, yPos, [239, 68, 68], 'Critical', report.severityDistribution.critical);
    drawLegend(60, yPos, [249, 115, 22], 'High', report.severityDistribution.high);
    drawLegend(110, yPos, [234, 179, 8], 'Medium', report.severityDistribution.medium);
    drawLegend(160, yPos, [59, 130, 246], 'Low', report.severityDistribution.low);

    // --- Defect Table ---
    yPos += 15;
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.setFont('helvetica', 'bold');
    doc.text('Detailed Defect List', 14, yPos);

    const tableColumn = ["ID", "Frame", "Type", "Severity", "Confidence", "Status"];
    const tableRows = defects.map(defect => [
        defect.id,
        defect.frameNumber,
        defect.typeLabel,
        defect.severityLabel,
        `${defect.confidence}%`,
        defect.reviewStatus
    ]);

    doc.autoTable({
        startY: yPos + 5,
        head: [tableColumn],
        body: tableRows,
        theme: 'grid',
        headStyles: { fillColor: [6, 182, 212] },
        styles: { fontSize: 8 },
        alternateRowStyles: { fillColor: [245, 245, 245] },
    });

    // --- Footer ---
    const totalPages = doc.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${totalPages} - ARIADOS AI Inspection System`, pageWidth / 2, pageHeight - 10, { align: 'center' });
    }

    doc.save(`${report.missionName.replace(/\s+/g, '_')}_Report.pdf`);
};
